<?php
if(count($items)){
?>
  <div class="row slider">
    <?php
    foreach ($items as $kI => $vI) {
      $multiImage = json_decode($vI['multi_image'], true);
      if(!$multiImage && $vI['image']){
        $multiImage[] = array('file'=>$vI['image'],'caption'=>$vI['title']);
      }
     ?>
      <div class="item-gallery col-sm-6 col-md-4 col-xl-3" style="cursor: pointer;">
        <div class="box-gallery">
          <?php
          if($multiImage){
          ?>
            <div class="image-gallery open-popup-gallery ">

              <?php
                foreach ($multiImage as $kS => $vS) {
                  $sActive = $kS == 0 ? 'class="active"':'';
                  $sImage = BASE_URL_MEDIA_IMAGE.'/'.$vS['file'];
                  $sImageThumb = BASE_URL_MEDIA_IMAGE.'/thumb/'.$vS['file'];
                 ?>
                  <a <?php echo $sActive; ?> style="background-image: url(<?php echo $sImageThumb; ?>);" attr-img="<?php echo $sImage; ?>"></a>
                <?php }
              ?>
            </div>
          <?php } ?>
          <div class="text-gallery">
            <h6>
              <?php 
              $formatCreated = $myLocale == 'en_US' ? 'F j, Y' : 'd/m/Y';
              echo $this->layoutHelper()->dateString($vI['created'], $formatCreated); 
              ?>
            </h6>

            <?php
            if($tab == "social-media"){ ?>
                <p><?php echo $this->truncate()->truncate($vI['intro'], 30); ?></p>
                <?php 
                  if($vI['more_info']){  
                    $hashTagArr = explode(" ", trim($vI['more_info']));
                    if($hashTagArr){
                 ?>
                    <div class="hastag-gallery">
                      <?php
                      foreach ($hashTagArr as $key => $value) { ?>
                        <a href="<?php echo $value; ?>"><?php echo $value; ?></a>
                      <?php } ?>
                    </div>
                <?php }
                  }
                ?>
            <?php }else{ ?>
              <div class="title">
                <h4>
                  <a href="javascript:;"><?php echo $vI['title'];?></a>
                </h4>
              </div>
            <?php }
            ?>
          </div>
        </div>
      </div>
    <?php }
    ?>
  </div>

  <?php
  if($paging){
  ?>
    <ul class="pagination text-center list-unstyled">
      <?php echo $paging->getPagingLinkFrontNextBackGalleryAjax($pagingParams); ?>
    </ul>
  <?php } ?>
<?php
}else{ ?>
  <div><?php echo $this->translate('No gallery found...'); ?></div>
<?php }
?>
