<?php
if($videos){
  $videoFix = $videos[0];
?>
  <!-- module 'Mod Banner Video' -->
  <section class="module mod-banner-video" data-module="bannervideo">
    <div class="content-banner">
      <div class="slider2">
        <?php
        foreach ($videos as $key => $value) {
          $vTitle = $value['title'];
          $vIntro = $value['intro'];
          $vIntroFix = $this->truncate()->truncate($vIntro, 20);

          $vEmbed = $value['subtitle']; //VideoID
          $vImage = BASE_URL_MEDIA_IMAGE.'/'.$value['image'];
         ?>
          <div class="bg-banner-video bg has-video" style="background-image: url(<?php echo $vImage; ?>);" attr-name="<?php echo $vTitle; ?>" attr-title="<?php echo $vIntroFix; ?>" attr-href="javascript:;">
              <?php
              if($vEmbed){
              ?>
                <div class="id1" attr-id-video="<?php echo $vEmbed; ?>"></div>
                <div class="icon-play">
                  <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/play.svg" alt="play">
                </div>
            <?php  } ?>
          </div>
        <?php }
        ?>
      </div>
    </div>
    <!-- module 'Mod Box Banner' -->
    <div class="container opacity">
      <section class="module mod-box-banner">
        <span class="box-name"></span>
        <a href="">
          <h3></h3>
        </a>
        <div class="group-box">
          <div class="stt">
            <p class="stt-box">1</p>
          </div>
          <div class="group-arraws"></div>
        </div>
      </section>
    </div>
  </section>
<?php } ?>