<?php
  if($amenities){
    $aContent = $amenities['body'];
    $aImage = BASE_URL_MEDIA_IMAGE.'/'.$amenities['image'];
?>
  <!-- module 'Mod Amenities' -->
  <section class="module mod-floorplan animation">
    <div class="container ani-bottom">
      <div class="name-floorplan">
        <h2 class="h1 text-center line"><?php echo $this->translate('AMENITIES'); ?></h2>
      </div>

      <section class="module mod-map-floorplan mod-map-floorplan-3">
        <div class="row info-map-floor">
          <div class="col-lg-4 box-right-floor">
            <div class="right-map active">
                <div class="item-right-floor">
                  <?php echo $aContent; ?>
                </div>
              </div>
          </div>
          <div class="col-lg-7 box-map-floor">
            <div class="img-map active">
              <img src="<?php echo $aImage; ?>" alt="map">
            </div>
          </div>
        </div>
      </section>

    </div>
  </section>
<?php } ?>
