<div class="form-group">
    <label class="col-sm-2 control-label" for="">Name <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Description</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('body')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('image', $form->get('image')->getValue(), '', array(400, 300), 0); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>