<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Location <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('category_multi')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Intro Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('intro')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Content: Short <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('body')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Content: Full <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('body1')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('image', $form->get('image')->getValue(), '', array(200, 200), 0); ?>
    </div>
</div>

<div class="form-group" id="block_image">
    <label class="col-sm-2 control-label" for="">Multi Image</label>
    <div class="col-sm-10">
        <?php echo $this->multiupload()->upload('multi_image', $form->get('multi_image')->getValue(), array('file_path' => BASE_URL . '/media/images')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>

<?php echo $this->ckeditor()->editor('body1'); ?>