<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title: define <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Intro Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('intro')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('image', $form->get('image')->getValue(), '', array(300, 150), 0); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>