<?php
$user = $this->user();
?>
<table class="table table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th class="tableColumnCheck"><input type="checkbox" value="1" id="checkall" class="checkall"/></th>
            <th><?php echo $this->layoutHelper()->header('id', $state); ?></th>
            <th><?php echo $this->layoutHelper()->header('title', $state); ?></th>
            <th><?php echo $this->layoutHelper()->header('identity', $state,'Overview Type'); ?></th>
            <th><?php echo $this->layoutHelper()->header('created', $state); ?></th>
            <th><?php echo $this->layoutHelper()->header('status', $state); ?></th>
            <!-- <th>AddByLang</th> -->
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item) : ?>
            <tr>
                <td><input type="checkbox" class="checkitem" name="data[Choose][]"  value="<?php echo $item['id']; ?>"/></td>
                <td><a href="<?php echo $this->url('postadmin', array('action' => 'edit', 'id' => $item['id'])) . '?type=' . $type; ?>"><?php echo $item['id']; ?></a></td>
                <td><a href="<?php echo $this->url('postadmin', array('action' => 'edit', 'id' => $item['id'])) . '?type=' . $type; ?>"><?php echo $this->escapeHtml($item['title']); ?></a></td>  
                 <td><?php echo $item['identity']; ?></td>              
                <td><?php echo $this->layoutHelper()->dateString($item['created']) ?></td>
                <td><?php echo $this->layoutHelper()->publishString($item['status']); ?></td>
                <!-- <td><?php //echo $factory->checkAddLanguage($item,'post'); ?></td> -->
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
