<div class="form-group">
    <label class="col-sm-2 control-label" for="">Category <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('category')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Brand name <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Logo</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('image', $form->get('image')->getValue(), '', array(300, 150), 0); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Website url</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle2')); ?>
        <div>
           <span style="font-size: 12px;"><i>Eg: https://google.com</i></span>
        </div>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Industry <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Location <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('category_multi')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle1')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Intro Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('intro')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Full Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('body')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('large_image', $form->get('large_image')->getValue(), '', array(300, 150), 0); ?>
    </div>
</div>

<div class="form-group" id="block_image">
    <label class="col-sm-2 control-label" for="">Product Slide</label>
    <div class="col-sm-10">
        <?php echo $this->multiupload()->upload('multi_image', $form->get('multi_image')->getValue(), array('file_path' => BASE_URL . '/media/images')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Home: is show?</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('home_is_show')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>
