<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Brand name <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Event date <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle1')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Event time <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle2')); ?>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label" for="">Intro Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('intro')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Full Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('body')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('image', $form->get('image')->getValue(), '', array(350, 200), 0); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Product Slide</label>
    <div class="col-sm-10">
        <?php echo $this->multiupload()->upload('multi_image1', $form->get('multi_image1')->getValue(), array('file_path' => BASE_URL . '/media/images'), true); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Home: is show?</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('home_is_show')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Home: banner slide</label>
    <div class="col-sm-10">
        <?php echo $this->multiupload()->upload('multi_image', $form->get('multi_image')->getValue(), array('file_path' => BASE_URL . '/media/images')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>