<div class="form-group">
    <label class="col-sm-2 control-label" for="">Page</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('identity')); ?>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label" for="">Holine <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>
<?php //echo $this->formHidden($form->get('csrf')); ?>