<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Link <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle')); ?>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label" for="">Icon Class <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('subtitle1')); ?>
    </div>
</div>



<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>