<script>
    var trans_Image_upload_missing = "<?php echo $this->translate('Image_upload_missing'); ?>";
    var trans_image = "<?php echo $this->translate('Image'); ?>";
    var trans_Uploadfile = "<?php echo $this->translate('Uploadfile'); ?>";
    var trans_Insert_photo = "<?php echo $this->translate('Insert_photo'); ?>";
    var trans_Delete_photo = "<?php echo $this->translate('Delete_photo'); ?>";
    var trans_InsertComment = "<?php echo $this->translate('InsertComment'); ?>";
    var trans_MaxCapacity = "<?php echo $this->translate('Max_Capacity'); ?>";
    var trans_ImageFormatError = "<?php echo $this->translate('ImageFormatError'); ?>";
    var trans_CommentMoreThan1000 = "<?php echo $this->translate('SaveContestSuccessful'); ?>";
    var flag_submission = true;
</script>
<?php  $myLocaleShort = $this->layout()->myLocaleShort; ?>
<?php if($myLocaleShort=='vi'): ?>
    <section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal.png)"></section>
<?php else: ?>
    <section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-en.png)"></section>
<?php endif; ?>

<div class="bg-sendshare bg">
    <!-- module 'Mod Form Share' -->
    <section class="module mod-form-share">
        <div class="container">
            <article>
                <div class="border-lv-2">
                    <div class="border-lv-3">
                        <h1><?php echo $this->translate('Submitions'); ?></h1>
                        <div class="form-share" name="form-share">
                            <div class="form-group select-box">
                                <label for="place"><?php echo $this->translate('Target'); ?>:</label>
                                <div class="col-input col-sm-7">
                                    <div class="msg-input">
                                        <select class="form-control selectpicker selectbox" id="goal-location" name="place">
                                            <option value="-1"><?php echo $this->translate('List_target'); ?></option>
                                            <option value="vn_84"><?php echo $this->translate('vn_84'); ?></option>
                                            <option value="kr_82"><?php echo $this->translate('kr_82'); ?></option>
                                            <option value="tw_886"><?php echo $this->translate('tw_886'); ?></option>
                                            <option value="jp_81"><?php echo $this->translate('jp_81'); ?></option>
                                            <option value="sg_65"><?php echo $this->translate('sg_65'); ?></option>
                                            <option value="kh_855"><?php echo $this->translate('kh_855'); ?></option>
                                            <option value="th_66"><?php echo $this->translate('th_66'); ?></option>
                                        </select>
                                        <div class="messages-error">
                                            <div><?php echo $this->translate('Target'); ?></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="note-upload">
                                <p><?php echo $this->translate('Upload_maximum'); ?>
                                    <br><span>*</span> ( <?php echo $this->translate('Max_Capacity'); ?> )</p>
                            </div>
                            <div class="group-parent-upload">
                                <div class="form-group group-upload-img">
                                    <label for=""><?php echo $this->translate('Image'); ?> <span class="sl">1</span> - </label>
                                    <input type="file" class="img-upload form-control">
                                    <img src="#" class="img-load d-none" style="max-width: 130px;" alt="">
                                    <a href="javascript:void(0);" class="btn btn-yellow"><?php echo $this->translate('Uploadfile'); ?></a>
                                    <div class="edit-upload">
                                        <a href="javascript:void(0);" class="add-img"><span class="icomoon icon-add2"></span> <?php echo $this->translate('Insert_photo'); ?></a>
                                        <a href="javascript:void(0);" class="add-del d-none"><?php echo $this->translate('Delete_photo'); ?></a>
                                    </div>
                                </div>
                            </div>
                            <div class="note-upload d-none" id="empty-upload-error">
                                <span><?php echo $this->translate('Image_upload_missing'); ?></span>
                            </div>
                            <div class="form-group row ">

                                <label for="title" class="col-sm-5" ><?php echo $this->translate('Subject'); ?></label>

                                <div class="col-input col-sm-7">
                                    <div class="msg-input ">
                                        <input type="text" class="form-control" id="share-title" name="sharetitle" placeholder="">
                                        <div class="messages-error">
                                            <div><?php echo $this->translate('Title_missing'); ?></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group coment">
                                <label for=""><?php echo $this->translate('Messages'); ?></label>
                                <textarea style="width: 100%; height: 150px; border-color: #CCC; padding-left: 5px;" id="share-content" name="sharecontent"></textarea>
                                <div class="messages-error" style="bottom: 40px;">
                                    <div></div>
                                </div>
                                <span><span>*</span> <?php echo $this->translate('Max_world'); ?></span>
                            </div>
                            <div class="group-btn">
                                <button id="contest-preview" class="btn btn-gray"><?php echo $this->translate('Review'); ?></button>
                                <button id="send-contest-btn" class="btn btn-primary"><?php echo $this->translate('Submitions'); ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </article>
        </div>
    </section>
</div>

<div id="pop-articel" class="mfp-control mfp-hide bzPopup">
    <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/img-amy.png" alt="" class="img-title">
    <div class="pop-content">
        <div class="pop-head text-center">
            <h4 id="preview-title"></h4>
            <h6><?php echo $this->translate('StoryOf'); ?> <strong id="preview-username"><?php echo $username; ?></strong></h6>
        </div>
        <div class="line"></div>
        <div class="articel-detail">
            <div class="articel-slider" id="article-slider">

            </div>
            <div id="preview-content">

            </div>
        </div>
        <div class="button text-center">
            <a href="javascript:void(0);" id="preview-send-contest" class="btn btn-primary"><?php echo $this->translate('Submitions'); ?></a>
        </div>
    </div>
</div>