<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Core\Module'                        => __DIR__ . '/Module.php',
    'Core\Controller\CoreController' => __DIR__ . '/src/Core/Controller/CoreController.php',
    'CoreTest\Framework\TestCase'        => __DIR__ . '/tests/Core/Framework/TestCase.php',
    'CoreTest\SampleTest'                => __DIR__ . '/tests/Core/SampleTest.php',
);