<?php
$factory = $this->factory();
$myLocale = $this->layout()->myLocale;
$myLocaleShort = $this->layout()->myLocaleShort;

$bannerPage = $factory->getPostByOptions('static_content_bannerpage', 1, $myLocale, array('identity'=>'retail_brand'));
$bannerPageImage = $bannerPage['image'] ? BASE_URL_MEDIA_IMAGE.'/'.$bannerPage['image'] : BASE_URL_SKIN_IMAGE.'/banner-brand.png';

?>
<!-- module 'Mod Banner Brand' -->
<section class="mod-banner-brand">
  <div class="banner-pr">
    <div class="banner-coll-brand bg" style="background-image: url(<?php echo $bannerPageImage; ?>);">
    </div>
    
    <!-- module 'Mod Box Search' -->
    <div class="container">
      <div class="mod-box-search">
        <h3>
          <?php echo $this->translate('We collaborate with most well-established brands'); ?>
        </h3>
        <form class="search-box" action="<?php echo $this->url('retail-brand', array('lang'=>$myLocaleShort)); ?>">
          <div class="form-group ">
            <div class="msg-input ">
              <input type="text" class="form-control" name="k" placeholder="<?php echo $this->translate('SEARCH'); ?>" value="<?php echo $keyword; ?>">
              <div class="messages-error">
                <div></div>
              </div>
            </div>
          </div>
          <button type="submit" class="submit-search">
            <span class="icomoon icon-icon-search"></span>
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

<?php
if($categoryList){
  foreach ($categoryList as $kCate => $vCate) {
    $brandList = $vCate['brandList'];
   ?>
    <!-- module 'Mod Slider Logo' -->
    <section class="module mod-slider-logo animation">
      <div class="container ani-bottom">
        <h5 class="name-logo"><?php echo $vCate['title']; ?></h5>
        <div class="mod-list-logo">
          <div class="list-logo slider-gallery" data-module="sliderGallery">
            <?php
            if($brandList){
            ?>
              <div class="row slider">
                <?php
                foreach ($brandList as $kB => $vB) {
                  $bUrl = $this->url('retail-branddetail', array('lang'=>$myLocaleShort, 'id'=>$vB['id'],'slug'=>$vB['slug']));
                  $bImage = BASE_URL_MEDIA_IMAGE.'/'.$vB['image'];
                  $floorIDs = json_decode($vB['category_multi'], true);

                  $multiImage = array();
                  if(!$multiImage && $vB['image']){
                      $multiImage[] = array('file'=>$vB['image'],'caption'=>$vB['title']);
                  }
                ?>
                  <div class="item-gallery col-sm-6 col-md-4 col-xl-3">
                    <div class="box-gallery">
                      <div class="image-gallery open-popup-gallery">
                        <?php
                          foreach ($multiImage as $kS => $vS) {
                            $sActive = $kS == 0 ? 'class="active"':'';
                            $sImage = BASE_URL_MEDIA_IMAGE.'/'.$vS['file'];
                            $sImageThumb = BASE_URL_MEDIA_IMAGE.'/thumb/'.$vS['file'];
                           ?>
                            <a <?php echo $sActive; ?> href="javascript:;" style="background-image: url(<?php echo $sImageThumb; ?>);" attr-img="<?php echo $sImage; ?>"></a>
                          <?php }
                        ?>
                        
                      </div>
                      <div class="text-gallery">
                        <span class="box-name"><?php
                            if($floorIDs){
                              $floorStr = '';
                              foreach ($floorIDs as $kF => $vF) {
                                $floor = $factory->getPostItem(array('id'=>$vF));
                                if($floor){
                                  $floorStr .= $floor['title'].', ';
                                }
                              }
                              echo rtrim($floorStr,', ');
                            }
                          ?></span>
                        <h4><?php echo $vB['title']; ?></h4>
                        <a href="<?php echo $bUrl; ?>" class="btn-custom"><?php echo $this->translate('visit our store'); ?></a>
                      </div>
                    </div>
                  </div>
                <?php }
                ?>
              </div>
            <?php } ?>
          </div>
        </div>
      </div>
    </section>
  <?php }
} ?>

