<!-- <div class="col-md-6">
    <div class="panel widget-messages panel-warning">
        <div class="panel-heading">
            <span class="panel-title"><i class="panel-title-icon fa fa fa-tasks"></i><?php echo $block->getTitle(); ?></span>
        </div>
        <div class="panel-body">
            <?php if ($data): ?>
                <?php foreach ($data as $post): ?>
                    <div class="message">
                        <a href="<?php echo $this->url('postadmin', array('action' => 'edit', 'id' => $post['id'])); ?>" title="" class="title"><?php print $post['title']; ?></a>
                        <div class="date">
                            <?php echo $this->layoutHelper()->dateString($post['created']) ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</div> -->
