<div class="form-group">
    <label class="col-sm-2 control-label" for="">Type</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('type')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Parent</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('parent_id')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Body</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('body')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('image', $form->get('image')->getValue(), '', array(450, 450), 0); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Large Image</label>
    <div class="col-sm-10">
        <?php echo $this->cropimageupload()->upload('large_image', $form->get('large_image')->getValue(), '', array(500, 500), 0); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>

<!--
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
<?php echo $this->formMedia($form->get('image')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Language</label>
    <div class="col-sm-10">
<?php echo $this->formSelect($form->get('language')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Body</label>
    <div class="col-sm-10">
<?php echo $this->formTextarea($form->get('body')); ?>
    </div>
</div>
-->