<div class="form-group">
    <label class="col-sm-2 control-label" for="">Group</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('group')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Name <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Type <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('type')); ?>
        <div><a href="javascript:;" class="contenttype_type_btn_edit">Edit</a></div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Description</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('description')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Ordering</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('ordering')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>
<?php //echo $this->formHidden($form->get('csrf')); ?>

<script type="text/javascript">
    $(document).ready(function(){
        var $identity = $('#type');
        if($identity.length > 0){
            if($identity.val()!==''){
                $identity.attr('readonly','true');
            }
        }  
    });
</script>