
<?php $this->layout()->setVariable('heading','Edit Group'); ?>
<?php
include_once(__DIR__ . '/partial/edittoolbar.phtml');
?>
<div class="clear">&nbsp;</div>
<div id="view-content">
    <div class="col-sm-12">
        <?php
        $form = $this->form;
        $messages = $form->getMessages();

        $form->prepare();
        echo $this->formMessenger()->showMessage($form);
        echo $this->form()->openTag($form);
        ?>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
                <div class="col-sm-10">
                    <?php echo $this->formInput($form->get('title')); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">Description</label>
                <div class="col-sm-10">
                    <?php echo $this->formTextarea($form->get('description')); ?>
                </div>
            </div>
        </div>
        <input type="hidden" name="callaction" id="callaction" value=""/>
        <?php echo $this->formHidden($form->get('id')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

