
<?php $this->layout()->setVariable('heading', 'Manage Group'); ?>
<?php
include_once(__DIR__ . '/partial/indextoolbar.phtml');
?>
<?php echo $this->flashMessenger(); ?>
<div class="clear"></div>
<div id="view-content">
    <div class="col-sm-12">
    <div class="table-primary">
        <form method="post" action="">
            <?php include_once(__DIR__ . '/partial/filter.phtml'); ?>
            <div class="clearfix">&nbsp;</div>
            <table class="table table-hover table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="tableColumnCheck"><input type="checkbox" value="1" id="checkall" class="checkall"/></th>
                        <th><?php echo $this->layoutHelper()->header('id', $state); ?></th>
                        <th><?php echo $this->layoutHelper()->header('title', $state); ?></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($items as $item) : ?>
                        <tr>
                            <td><input type="checkbox" class="checkitem" name="data[Choose][]"  value="<?php echo $item['id']; ?>"/></td>
                            <td><a href="<?php echo $this->url('groupadmin', array('action' => 'edit', 'id' => $item['id'])); ?>"><?php echo $item['id']; ?></a></td>
                            <td><?php echo $this->escapeHtml($item['title']); ?></td>
                            <td><a href="<?php echo $this->url('permissionadmin', array('groupid'=>$item['id'])) ?>">permissions</a></td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <div class="pagination-container">
                <?php
                echo $paging->getPagingLink();
                echo $paging->getPagingInfo();
                ?>
            </div>
            <input type="hidden" name="callaction" id="callaction" value=""/>
            <input type="hidden" name="choose[]" value=""/>
            <input type="hidden" name="filter_order" id="filter_order" value="<?php echo $filter_order; ?>"/>
            <input type="hidden" name="filter_order_Dir" id="filter_order_Dir" value="<?php echo $filter_order_Dir; ?>"/>
        </form>
    </div>
</div>
</div>