<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <script> var baseurl = "<?php echo BASE_URL; ?>"; </script>
        <base href="<?php echo BASE_URL; ?>/"/>
        <?php echo $this->headTitle(' '. $this->translate('CMS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/skin/admin/mytheme/css/style.css')
                        ->prependStylesheet($this->basePath() . '/skin/common/jsoneditor/jsoneditor.css')
                        ->prependStylesheet($this->basePath() . '/skin/common/datepicker/css/datepicker.css')
                        ->prependStylesheet($this->basePath() . '/skin/admin/mytheme/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/skin/admin/mytheme/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/skin/admin/mytheme/css/bootstrap.min.css')
                        
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/skin/admin/mytheme/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/skin/admin/mytheme/js/jquery-1.8.3.min.js') ?>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/jquery.validate.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/ejs_production.js"></script>
    </head>
    <body role="document">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
             <?php echo $this->partial('partial/admin/header', array('user'=>$this->user)); ?>
        </div>
        <?php if($this->heading): ?>
        <div class="navbar navbar-default navbar-heading"><div class="container-fluid"><h3><?php echo $this->heading; ?></h3></div></div>
        <?php endif; ?>
        <div class="container-fluid">
            <?php echo $this->content; ?>
            <hr>
            <?php echo $this->partial('partial/admin/footer'); ?>
           
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/jquery.slug.js"></script>
        
        <script src="<?php echo $this->basePath() ?>/skin/common/jqueryfileupload/jquery.ui.widget.js"></script>
        <script src="<?php echo $this->basePath() ?>/skin/common/jqueryfileupload/jquery.iframe-transport.js"></script>
        <script src="<?php echo $this->basePath() ?>/skin/common/jqueryfileupload/jquery.fileupload.js"></script>
        
        <script src="<?php echo $this->basePath() ?>/skin/common/jsoneditor/json2.js"></script>
        <script src="<?php echo $this->basePath() ?>/skin/common/jsoneditor/jquery.jsoneditor.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/jsoneditor.js"></script>
        <script src="<?php echo $this->basePath() ?>/skin/common/datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/common.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/app.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/file.js"></script>
        
        
    </body>
</html>
