<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <script> var baseurl = "<?php echo BASE_URL; ?>"; </script>
        <?php echo $this->headTitle(' '. $this->translate('CMS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/skin/frontend/mytheme/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/skin/frontend/mytheme/css/style.css')
                        ->prependStylesheet($this->basePath() . '/skin/frontend/mytheme/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/skin/frontend/mytheme/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/skin/frontend/mytheme/js/jquery-1.7.2.min.js') ?>
    </head>
    <body><?php //print_r($user) ; ?>
        <div class="navbar navbar-fixed-top">
             <?php //echo $this->partial('partial/admin/header', array()); ?>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <?php echo $this->partial('partial/admin/footer'); ?>
           
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
         <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/bootstrap.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/jquery.validate.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/jquery.slug.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/common.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath()  ?>/skin/admin/mytheme/js/app.js"></script>
    </body>
</html>
