<?php 
$factory = $this->factory();
//$categories = $factory->getCategory();
?>
<ul class="navigation">
    <li>
	<a href="<?php echo $this->url('admin') ?>"><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span></a>
    </li>

    <li class="mm-dropdown">
        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog fa-fw"></i>&nbsp;<span><?php echo $this->translate('Configuration') ?></span></a>
        <ul>
            <li><a href="<?php echo $this->url('settingadmin'); ?>"><span>Settings</span></a></li>
            <li><a href="<?php echo $this->url('languageadmin'); ?>"><span>Languages</span></a></li>
        </ul>
    </li>

    <li class="mm-dropdown">
        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-book fa-fw"></i>&nbsp;<span>Contest</span></a>
        <ul>
            <li><a href="<?php echo $this->url('contest-admin'); ?>"><span>Contest Listing</span></a></li>

        </ul>
    </li>

    <li class="mm-dropdown">
        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-book fa-fw"></i>&nbsp;<span>Other</span></a>
        <ul>
            <li><a href="<?php echo $this->url('contactadmin').'?type=subscribe'; ?>"><span>Subscribe</span></a></li>
            <li><a href="<?php echo $this->url('contactadmin').'?type=fitness_join_us'; ?>"><span>Fitness: join us</span></a></li>
        </ul>
    </li>

    <li class="mm-dropdown">
        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-fw"></i>&nbsp;<span>People</span></a>
        <ul>
            <li><a href="<?php echo $this->url('useradmin'); ?>"><span>Admins</span></a></li>
        </ul>
    </li>
</ul>
