<div class="form-group">
    <label class="col-sm-2 control-label" for="">UserId</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('user_id')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Title <span class="asterisk">*</span></label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Slug</label>
    <div class="col-sm-10">
        <?php echo $this->formInput($form->get('slug')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label" for="">Full Text</label>
    <div class="col-sm-10">
        <?php echo $this->formTextarea($form->get('descriptions')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" for="">Image</label>
    <div class="col-sm-10">
    <?php $imageString = $data['images'];
    $imageArray= explode(',',$imageString);
    ?>
    <?php foreach($imageArray as $value):  ?>
    <img style="max-width: 400px;" src="<?php echo BASE_URL_MEDIA.'/images/'.$value; ?>">
        <?php endforeach; ?>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label" for="">Status</label>
    <div class="col-sm-10">
        <?php echo $this->formSelect($form->get('status')); ?>
    </div>
</div>
<?php //echo $this->formHidden($form->get('csrf')); ?>