<?php
$myLocale = $this->layout()->myLocale;
$myLocaleShort = $this->layout()->myLocaleShort;
$user = $this->user();
?>
<?php if($myLocaleShort=='vi'): ?>
    <section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal.png)">
        <div class="logo-tn">
            <a href="https://thanhnien.vn/doi-song/vietjet-air-ket-noi-yeu-thuong-voi-giai-thuong-dac-biet-nhat-tu-truoc-den-nay-1027482.html?utm_source=LoveConnection&utm_medium=HeadLogo-click" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/logo-tn.png" alt="logo-tn"></a>
        </div>
    </section>
<?php else: ?>
    <section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-en.png)">
        <div class="logo-tn">
            <a href="https://thanhnien.vn/doi-song/vietjet-air-ket-noi-yeu-thuong-voi-giai-thuong-dac-biet-nhat-tu-truoc-den-nay-1027482.html?utm_source=LoveConnection&utm_medium=HeadLogo-click" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/logo-tn.png" alt="logo-tn"></a>
        </div>
    </section>
<?php endif; ?>


<!-- module 'Mod Slide Detail' -->
<!-- module 'Mod Intro' -->
<section class="module mod-intro">
    <div class="container">
        <article class="content-slide">
            <div class="heading-intro">
                <?php if($myLocaleShort=='vi'): ?>
                <h1>Bay là Thích ngay!<br> Bay khắp Việt Nam & Quốc tế</h1>
                <?php else: ?>
                    <h1>Enjoy flying all over Vietnam and across Asia</h1>
                <?php endif; ?>
            </div>
            <div class="status-detail">
                <?php echo html_entity_decode($about['body']); ?>
                <div class="buy-ticket">
                    <span class="place-buy"><?php echo $this->translate('Buy_location'); ?></span>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="row">
                                <div class="col-lg-6">
                                    <a href="https://www.vietjetair.com" style="white-space: nowrap;"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/icon-eart.png" alt="icon"> www.vietjetair.com</a>
                                </div>
                                <div class="col-lg-6">
                                    <a href="https://www.vietjetair.com" style="white-space: nowrap;" ><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/icon-phone.png" alt="icon"> www.vietjetair.com</a>
                                </div>
                                <div class="col-lg-12">
                                    <a href="https://www.facebook.com/vietjetairvietnam"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/icon-fb.png" alt="icon"> facebook.com/vietjetairvietnam </a><?php echo ' '. $this->translate('about_text');   ?>
                                    <p><?php echo $this->translate('PaymentInfo');   ?></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/img-qr.png" alt="qr">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-share-detail">
                <div class="social-share">
                    <span class="share">SHARE :</span> <div class="social">
                        <ul>
                            <li>
                                <a rel="noopener" target="_blank" href="javascript:void(0)" onclick="App.VoteShare.shareSite()">
                                    <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/icon-fb.svg" alt="">
                                </a>
                            </li>
                            
                        </ul>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <?php if (@$user && @$user['id']): ?>
                    <a class="btn btn-primary" href="javascript:void(0);" onclick="App.Site.goToContestSubmit(<?php echo @$user['id']; ?>);"><?php echo $this->translate('Submitions'); ?></a>
                <?php else: ?>
                    <a class="btn btn-primary" href="javascript:void(0);" onclick="App.Popup.openLogin();"><?php echo $this->translate('Submitions'); ?></a>
                <?php endif; ?>
            </div>
        </article>
    </div>
</section>