<?php
$myLocaleShort = $this->layout()->myLocaleShort;
?>

<?php  if($myLocaleShort=='vi'): ?>
	<section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal.png)">
		<div class="banner-internal-mb d-block d-md-none">
			<img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-mb-vi.jpg" alt="">
		</div>
		<div class="logo-tn">
			<a href="https://thanhnien.vn/doi-song/vietjet-air-ket-noi-yeu-thuong-voi-giai-thuong-dac-biet-nhat-tu-truoc-den-nay-1027482.html?utm_source=LoveConnection&utm_medium=HeadLogo-click" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/logo-tn.png" alt="logo-tn"></a>
		</div>
	</section>
<?php else: ?>
	<section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-en.png)">
		<div class="banner-internal-mb d-block d-md-none">
			<img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-mb-en.jpg" alt="">
		</div>
		<div class="logo-tn">
			<a href="https://thanhnien.vn/doi-song/vietjet-air-ket-noi-yeu-thuong-voi-giai-thuong-dac-biet-nhat-tu-truoc-den-nay-1027482.html?utm_source=LoveConnection&utm_medium=HeadLogo-click" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/logo-tn.png" alt="logo-tn"></a>
		</div>
	</section>
<?php endif; ?>

<div class="container">
</div>
<div class="bg-body-trip">
	<!-- module 'Mod Trip' -->
	<section class="module mod-trip">
		<div class="container">
			<h1><?php echo $this->translate('Flight_Information'); ?></h1>
			<div class="arrow-right d-md-none">
				<span class="icomoon icon-chevron-right"></span>
			</div>
			<div class="table-status custom-scroll-horizontal">
				<?php echo $flightinformation['body'] ?>
			</div>
		</div>
	</section>

</div>
