<?php if($myLocaleShort=='vi'): ?>
	<section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal.png)"></section>
<?php else: ?>
	<section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-en.png)"></section>
<?php endif; ?>

<div class="container">
</div>
<div class="bg-body-trip">
	<!-- module 'Mod Trip' -->
	<section class="module mod-trip">
		<div class="container">
			<h1><?php echo $this->translate('Flight_Information'); ?></h1>
			<div class="table-status">
				<?php echo $flightinformation['body'] ?>
			</div>
		</div>
	</section>

</div>
</main>