<?php
$myLocaleShort = $this->layout()->myLocaleShort;
?>
<?php if($myLocaleShort=='vi'): ?>
    <section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal.png)">
        <div class="logo-tn">
            <a href="https://thanhnien.vn/doi-song/vietjet-air-ket-noi-yeu-thuong-voi-giai-thuong-dac-biet-nhat-tu-truoc-den-nay-1027482.html?utm_source=LoveConnection&utm_medium=HeadLogo-click" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/logo-tn.png" alt="logo-tn"></a>
        </div>
    </section>
<?php else: ?>
    <section class="module mod-banner-internal bg" style="background-image: url(<?php echo BASE_URL_SKIN_IMAGE; ?>/banner-internal-en.png)">
        <div class="logo-tn">
            <a href="https://thanhnien.vn/doi-song/vietjet-air-ket-noi-yeu-thuong-voi-giai-thuong-dac-biet-nhat-tu-truoc-den-nay-1027482.html?utm_source=LoveConnection&utm_medium=HeadLogo-click" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/logo-tn.png" alt="logo-tn"></a>
        </div>
    </section>
<?php endif; ?>

<div class="bg-sendshare bg">
    <!-- module 'Mod Content Conection' -->
    <section class="module mod-content-conection">
        <div class="container">
            <article>
                    <?php echo $rule['body']; ?>
                </div>
            </article>
        </div>
    </section>

</div>