<?php
$myLocaleShort = $this->layout()->myLocaleShort;
if($item['image']){
	$iImage = BASE_URL_MEDIA_IMAGE.'/'.$item['image']; ?>
	<!-- module 'Mod Banner' -->
	<section class="mod-banner animation" data-module="bannervideo">
	  	<div class="card-header banner-pr ani-bottom">
		    <div class="banner-coll bg" style="background-image: url(<?php echo $iImage; ?>);">
		    </div>
	  	</div>
	</section>
<?php } ?>

<div class="container">  
  	<div class="content-promotion ani-bottom">
	  	<div class="row">
		    <div class="col-md-7 col-left">
		      <h1><?php echo $item['title']; ?></h1>
		      <div>
		      	<?php echo $item['body']; ?>
		      </div> 
		    </div>
		    
		    <div class="col-md-5 col-right">
			  	<div class="mod-right-promotion">
				  	<?php echo $item['body1']; ?>
				</div>
				<a href="<?php echo $this->url('fitness-overview', array('lang'=>$myLocaleShort)); ?>" class="btn btn-back"><?php echo $this->translate('BACK TO FITNESS'); ?></a>
		    </div>
	  	</div>
	</div>
</div>