<?php
$template = 'post';
$type = $form->get('type')->getValue();
if ($type) {
    $factory = $this->factory();
    $contentType = $factory->getContentTypeByType($type);
    $titleForm = $contentType['title'];
} else {
    $titleForm = 'Content';
}
$this->layout()->setVariable('heading', 'Edit ' . ucfirst($titleForm));
?>

 <?php 
 if (file_exists(__DIR__ ."/".$template. '/partial/edittoolbar_'.$type.'.phtml')) {
        include(__DIR__ ."/".$template. '/partial/edittoolbar_'.$type.'.phtml');
    } elseif (file_exists(__DIR__ . "/".$template."/partial/edittoolbar.phtml")) {
        include(__DIR__ ."/".$template. '/partial/edittoolbar.phtml');
    }
 ?>

<?php echo $this->flashMessenger(); ?>
<div class="clear">&nbsp;</div>
<div id="view-content">
    <div class="col-sm-12">
        <?php
        $form = $this->form;

        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formMessenger()->showMessage($form);
        ?>

        <div class="panel-body">
            <!--<?php 
            //$linkAddLang = $factory->checkAddLanguage($data,'post');
            if($linkAddLang != '---'){
             ?>
                <div style="text-align: center; padding: 10px 0 30px; font-weight: bold; border-bottom: 1px solid #ccc;">
                   [ Other language for this content: <?php //echo $linkAddLang; ?> ]
                </div>
            <?php } ?>
            <br> -->

            <?php
            if (file_exists(__DIR__ . "/".$template."/".$type."_form.phtml")) {
                include_once(__DIR__ . "/".$template."/".$type."_form.phtml");
            } elseif (file_exists(__DIR__ . "/".$template."/form_custom.phtml")) {
                include_once(__DIR__ . "/".$template."/form_custom.phtml");
            }
            //include_once(__DIR__ .  "/".$template. '/partial/panel.phtml');
            ?>
        </div>

        <?php echo $this->formHidden($form->get('lang_group')); ?>
        <?php echo $this->formHidden($form->get('id')); ?>
        <?php echo $this->formHidden($form->get('type')); ?>
        <input type="hidden" name="callaction" id="callaction" value=""/>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<div class="clear">&nbsp;</div>

 <?php 
 if (file_exists(__DIR__ ."/".$template. '/partial/edittoolbar_'.$type.'.phtml')) {
        include(__DIR__ ."/".$template. '/partial/edittoolbar_'.$type.'.phtml');
    } elseif (file_exists(__DIR__ . "/".$template."/partial/edittoolbar.phtml")) {
        include(__DIR__ ."/".$template. '/partial/edittoolbar.phtml');
    }
 ?>
 
<?php echo $this->ckeditor()->editor(); ?>