<div class="col-md-3"></div>
<div class="col-md-6">
    <h1 class="text-center">Sign in</h1>
    <?php
    if($login) {
        echo '<br/><div class="text-center">Xin chào, '.$login['name'].'<br/>';
        echo $logout.'</div>';
    }else{
    ?>
    <div class="row col-md-12 social-container">
        <div class="col-md-6">
            <div class="fb-login-btn text-right">
                <a class="btn-login-facebook" href="javascript:void(0)">Login With Facebook</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="google-signin"></div>
        </div>
    </div>
    <div class="row col-md-12">
        <hr/>
        <div class="col-md-2"></div>
        <div class="col-md-8">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" id="login-email" placeholder="Enter email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="password">Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="login-password" placeholder="Enter email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <button id="login-btn">Đăng Nhập</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    }
    ?>
<div class="col-md-3"></div>



