<div class="col-sm-12">
    <div class="panel-group">
    <div class="panel">
        <div class="panel-heading">
            <a class="accordion-toggle" data-toggle="collapse" href="#collapseLayout">
                    Layout
                </a>
        </div>
        <div id="collapseLayout" class="panel-collapse collapse in" style="height: auto">
            <div class="panel-body">
                 <div class="form-group">
                    <label class="col-sm-2 control-label" for="">Layout</label>
                    <div class="col-sm-10">
                        <?php echo $this->formInput($form->get('params[layout]')); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
