<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EDM</title>
</head>

<body style="margin:0px; padding:0px;">
<table style="width:100%;margin:0px auto;padding:0px; background:#fff;
      line-height:12px; font-family: 'Arial'; max-width: 724px; position:
      relative; opacity: 1; top: 0px; left: 0px;" align="center" cellpadding="0"
       cellspacing="0" border="0">
    <tr align="top">
        <td align="center" valign="top">
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="32" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo.jpg"style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="400" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/title.jpg"style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="64" style="font-size:10px; line-height:10px;">&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="font-size:10px; line-height:10px;">
                        <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                line-height:12px; max-width: 724px; position: relative; opacity: 1;
                top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                               border="0">
                            <tr>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                                <td width="644" style="font-size:10px; line-height:10px;">
                                    <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                      line-height:12px; max-width: 724px; position: relative; opacity: 1;
                      top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                                           border="0">
                                        <tr>
                                            <td style="font-size:17px; line-height:32px;">
                                                <span style="text-align: center; color:#c80000; font-size: 26px; display: inline-block;">VIETJET - BÀI DỰ THI CỦA BẠN KHÔNG ĐƯỢC DUYỆT!</span>
                                                <br>
                                                <br>
                                                <span>Chào bạn,</span>
                                                <br>
                                                <br>
												
												<span style="text-align: justify;display: inline-block;">VIETJET cảm ơn bạn đã tham dự chương trình "KẾT NỐI YÊU THƯƠNG, YÊU LÀ PHẢI TỚI". Rất tiếc, bài dự thi của bạn không được duyệt vì chứa nội dung nhạy cảm không phù hợp với tiêu chí chương trình.</span>
												
                                                <span style="text-align: justify;display: inline-block;">Mời bạn tham khảo điều kiện và thể lệ tham gia chương trình tại: <br>
												
												
                              <a href="<?php echo  BASE_URL.$this->url('rules',array('lang'=>'vi')) ?>" style="text-decoration: none; color: #c80000;" target="_blank"><?php echo  BASE_URL. $this->url('rules',array('lang'=>'vi')) ?></a>
                            </span>
                                                <br>
                                              
                            <span>
                              Thời gian tham dự:  <a style="text-decoration: none; color: #c80000;">từ nay - 27/12/2018</a>.
                            </span>
                                                <br>
                                                  <br>

                                                <span>Hãy tham gia ngay để có cơ hội nhận vé khứ hồi miễn phí các chặng giữa Việt Nam và Nhật Bản, Hàn Quốc, Đài Loan, Hong Kong, Thái Lan, Singapore, Malaysia, Campuchia.</span>
                                                <br>
								   <span>Đặc biệt, chương trình giờ vàng khuyến mãi hàng triệu vé 0 đồng luôn chào đón bạn từ 12h - 14h mỗi ngày tại www.vietjetair.com, từ nay đến 15/2/2019, áp dụng tất cả đường bay khắp Việt Nam & 10 nước Châu Á.     <br><br>
Hẹn gặp bạn trên các chuyến bay vui vẻ cùng Vietjet.</span>
                                                <br>				
                                              
                                                <br>
                                                <span style="text-align: right; font-weight: 700; display: inline-block; width: 100%;">Trân trọng,</span>
                                                <br>
                            <span style="padding-top: 20px;text-align: right; font-weight: 700; display: inline-block; width: 100%;">
                              <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo-small.jpg" alt="">
                            </span>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:10px; line-height:10px;">
                        <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/img-footer.jpg" alt="">
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>

</html>