<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EDM</title>
</head>

<body style="margin:0px; padding:0px;">
<table style="width:100%;margin:0px auto;padding:0px; background:#fff;
      line-height:12px; font-family: 'Arial'; max-width: 724px; position:
      relative; opacity: 1; top: 0px; left: 0px;" align="center" cellpadding="0"
       cellspacing="0" border="0">
    <tr align="top">
        <td align="center" valign="top">
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="32" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo.jpg"style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="400" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/title.jpg"style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="64" style="font-size:10px; line-height:10px;">&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="font-size:10px; line-height:10px;">
                        <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                line-height:12px; max-width: 724px; position: relative; opacity: 1;
                top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                               border="0">
                            <tr>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                                <td width="644" style="font-size:10px; line-height:10px;">
                                    <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                      line-height:12px; max-width: 724px; position: relative; opacity: 1;
                      top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                                           border="0">
                                        <tr>
                                            <td style="font-size:17px; line-height:32px;">
                                                <span style="text-align: center; color:#c80000; font-size: 26px; display: inline-block;">BÀI DỰ THI CỦA BẠN ĐÃ ĐƯỢC DUYỆT THÀNH CÔNG</span>
                                                <br>
                                                <br>
                                                <span>Chào bạn,</span>
                                                <br>
                                                <br>
                                                <span style="text-align: justify;display: inline-block;">Bài dự thi của bạn đã được duyệt thành công tại link bên dưới <br><a href="<?php echo $this->contest_url; ?>" style="text-decoration: none; color: #c80000;" target="_blank"><?php echo $this->contest_url; ?></a></span>
                                                <br>
                                                <br>
                            <span style="text-align: justify;display: inline-block;">
                              Bạn hãy chia sẻ bài dự thi trên tài khoản mạng xã hội cá nhân và kêu gọi bạn bè bình chọn cho bạn để tham gia Hành trình <a style="text-decoration: none; color: #c80000;">“ KẾT NỐI YÊU THƯƠNG, YÊU LÀ PHẢI TỚI”</a>
                            </span>
                                                <br>  <br>
                                               
                            <span>
                              Thể lệ cuộc thi: <a href="<?php echo  BASE_URL.$this->url('rules',array('lang'=>'vi')) ?>" style="text-decoration: none; color: #c80000;" target="_blank"><?php echo  BASE_URL. $this->url('rules',array('lang'=>'vi')) ?></a>
                            </span>
                                                <br>
                                              
                            <span>
                              Thời gian tham dự:  <a style="text-decoration: none; color: #c80000;">từ nay - 27/12/2018</a>.
                            </span>
                                                <br>
                                                  <br>

                                                <span>Cảm ơn bạn đã tham dự và hẹn gặp bạn trên các chuyến bay vui vẻ cùng Vietjet</span>
                                                <br>
                                              
                                                <br>
                                                <span style="text-align: right; font-weight: 700; display: inline-block; width: 100%;">Trân trọng,</span>
                                                <br>
                            <span style="padding-top: 20px;text-align: right; font-weight: 700; display: inline-block; width: 100%;">
                              <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo-small.jpg" alt="">
                            </span>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:10px; line-height:10px;">
                        <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/img-footer.jpg" alt="">
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>

</html>