<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EDM</title>
</head>

<body style="margin:0px; padding:0px;">
<table style="width:100%;margin:0px auto;padding:0px; background:#fff;
      line-height:12px; font-family: 'Arial'; max-width: 724px; position:
      relative; opacity: 1; top: 0px; left: 0px;" align="center" cellpadding="0"
       cellspacing="0" border="0">
    <tr align="top">
        <td align="center" valign="top">
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="32" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo.jpg"style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="400" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/title-en.jpg"style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="64" style="font-size:10px; line-height:10px;">&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="font-size:10px; line-height:10px;">
                        <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                line-height:12px; max-width: 724px; position: relative; opacity: 1;
                top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                               border="0">
                            <tr>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                                <td width="644" style="font-size:10px; line-height:10px;">
                                    <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                      line-height:12px; max-width: 724px; position: relative; opacity: 1;
                      top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                                           border="0">
                                        <tr>
                                            <td style="font-size:17px; line-height:32px;">
                                                <span style="text-align: center; color:#c80000; font-size: 26px; display: inline-block;">WELCOME TO THE "LOVE CONNECTION - LOVE IS REAL TOUCH" CAMPAIGN OF VIETJET</span>
                                                <br>
                                                <br>
                                                <span>Dear friend,</span>
                                                <br>
                                                <br>
                                                <span style="text-align: justify;display: inline-block;">Welcome! You have signed up successfully at <a href="https://loveconnection.vietjetair.com" style="text-decoration: none; color: #c80000;" target="_blank"><?php echo BASE_URL; ?></a>.</span>
                                                <br>
                                                <br>
                            <span style="text-align: justify;display: inline-block;">
                              Kindly read the Terms & Conditions carefully and submit your story as to win chances of receiving our free return tickets applied to flight routes between <a style="text-decoration: none; color: #c80000;">Vietnam & internation destinations (Japan, Korea, Taiwan, Malaysia, Thailand, Cambodia, Hongkong, Singapore & China)</a>.
                            </span>

                                                <br><br>
                            <span style="display: inline-block;">
                              The campaign's Terms & Conditions: <a href="<?php echo  BASE_URL. $this->url('rules',array('lang'=>'en')) ?>" style="text-decoration: none; color: #c80000;" target="_blank"><?php echo  BASE_URL.$this->url('rules',array('lang'=>'en')) ?></a>
                            </span>

                                                <br> <br>
                            <span>Especially, the promotion program from just USD 0 tickets await you from 12PM - 2PM (Vietnamese time)  every day at www.vietjetair.com, from now until 15/2/2019, apply to all routes throughout Vietnam & 10 Asian countries. <br><br>
                              Don't miss out. We look forward to seeing you onboard with Vietjet!</span>
                                                <br>

                                                <br>
                                                <br>
                            <span style="text-align: right; font-weight: 700; display: inline-block; width: 100%;">Best regards, <br>
                              Vietjet</span>
                                                <br>
                            <span style="padding-top: 20px;text-align: right; font-weight: 700; display: inline-block; width: 100%;">
                              <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo-small.jpg" alt="">
                            </span>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:10px; line-height:10px;">
                        <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/img-footer.jpg" alt="">
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>

</html>