<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EDM</title>
</head>

<body style="margin:0px; padding:0px;">
<table style="width:100%;margin:0px auto;padding:0px; background:#fff;
      line-height:12px; font-family: 'Arial'; max-width: 724px; position:
      relative; opacity: 1; top: 0px; left: 0px;" align="center" cellpadding="0"
       cellspacing="0" border="0">
    <tr align="top">
        <td align="center" valign="top">
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="32" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo.jpg" style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="400" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/title.jpg" style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="64" style="font-size:10px; line-height:10px;">&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="font-size:10px; line-height:10px;">
                        <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                line-height:12px; max-width: 724px; position: relative; opacity: 1;
                top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                               border="0">
                            <tr>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                                <td width="644" style="font-size:10px; line-height:10px;">
                                    <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                      line-height:12px; max-width: 724px; position: relative; opacity: 1;
                      top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                                           border="0">
                                        <tr>
                                            <td style="font-size:17px; line-height:32px;">
                                                <span style="text-align: center; color:#c80000; font-size: 26px; display: inline-block;">CONGRATULATION! YOU ARE THE WINNER OF “LOVE CONNECTION - LOVE IS REAL TOUCH” CAMPAIGN</span>
                                                <br>
                                                <br>
                                                <span>Dear friend</span>
                                                <br><br>

                                                <span style="text-align: justify;display: inline-block;">Vietjet would like to congratulate you for being the winner of <a style="text-decoration: none; color: #c80000;">"Love Connection – Love Is Real Touch"</a> campaign.</span>
                                                <br>
												
												<span style="text-align: justify;display: inline-block;">Vietjet would like to invite you to join the flight with us with belowed link:<br>
												<span style="text-align: justify;display: inline-block;">Flight Information:<br><b style="text-align: center; color:#c80000; display: inline-block;"><?php echo $this->destination; ?></b> <br>
												<span style="text-align: justify;display: inline-block;">Please inform us your detail information by replying this email with:

<ul>
  <li>Your full name:</li>
  <li>Phone Number:  </li>
  <li>Detail Address:</li>
    <li>Scaned passport:</li>
	    <li>Arrival date:</li>
	  <li>* Your second phone number (in case we can't reach you):</li>
</ul>
											
												</span><br>
												<span style="text-align: justify;display: inline-block;">Note:
												
	<ul>
  <li>Please prepare your application visa (if any) for internationnal flights on time to not miss your flight. </li>
  <li>Please follow closely our Conditions of carriage at www.vietjetair.com</li>
  <li> Please confirm the return date no later than 15/02/2019. </li>
    <li>The booked return ticket cannot be changed after confirmation.</li>

</ul>
														
										
											
												</span>
												
         
                                                <br>
                            <span style="text-align: justify;display: inline-block;">
                             Thank you for your trust and traveling with us. We look forward to seeing you onboard with Vietjet!.

                            </span>
                                                <br>
                                                <br>
                                                <br>
                                                <span style="text-align: right; font-weight: 700; display: inline-block; width: 100%;">Best Regard,</span>
                                                <br>
                            <span style="padding-top: 20px;text-align: right; font-weight: 700; display: inline-block; width: 100%;">
                              <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo-small.jpg" alt="">
                            </span>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:10px; line-height:10px;">
                        <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/img-footer.jpg" alt="">
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>

</html>