<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EDM</title>
</head>

<body style="margin:0px; padding:0px;">
<table style="width:100%;margin:0px auto;padding:0px; background:#fff;
      line-height:12px; font-family: 'Arial'; max-width: 724px; position:
      relative; opacity: 1; top: 0px; left: 0px;" align="center" cellpadding="0"
       cellspacing="0" border="0">
    <tr align="top">
        <td align="center" valign="top">
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="32" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo.jpg" style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="400" style="font-size:10px; line-height:10px;">
                        <a href="" target="_blank"><img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/title.jpg" style="display:block; width: 100%;" alt=""></a>
                    </td>
                </tr>
            </table>
            <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
            line-height:12px; max-width: 724px; position: relative; opacity: 1;
            top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                   border="0">
                <tr>
                    <td height="64" style="font-size:10px; line-height:10px;">&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="font-size:10px; line-height:10px;">
                        <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                line-height:12px; max-width: 724px; position: relative; opacity: 1;
                top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                               border="0">
                            <tr>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                                <td width="644" style="font-size:10px; line-height:10px;">
                                    <table style="width:100%;margin:0px auto;padding:0px; background:#fff;
                      line-height:12px; max-width: 724px; position: relative; opacity: 1;
                      top: 0px; left: 0px;" align="center" cellpadding="0" cellspacing="0"
                                           border="0">
                                        <tr>
                                            <td style="font-size:17px; line-height:32px;">
                                                <span style="text-align: center; color:#c80000; font-size: 26px; display: inline-block;">CHÚC MỪNG BẠN ĐÃ THẮNG GIẢI THƯỞNG CUỘC THI "KẾT NỐI YÊU THƯƠNG - YÊU LÀ PHẢI TỚI"</span>
                                                <br>
                                                <br>
                                                <span>Chào bạn,</span>
                                                <br><br>

                                                <span style="text-align: justify;display: inline-block;">Vietjet chúc mừng bạn là người chiến thắng, được lựa chọn tham gia Hành trình <a style="text-decoration: none; color: #c80000;">"KẾT NỐI YÊU THƯƠNG - YÊU LÀ PHẢI TỚI"</a>, khám khá 10 nước Châu Á cùng Vietjet.</span>
                                                <br>
												
												<span style="text-align: justify;display: inline-block;">Vietjet xin mời Bạn sẵn sàng tham gia Hành trình bay như sau: <br>
												<span style="text-align: justify;display: inline-block;">Thông tin chuyến bay: <br><b style="text-align: center; color:#c80000; display: inline-block;"><?php echo $this->destination; ?></b> <br>
												<span style="text-align: justify;display: inline-block;">Vui lòng cung cấp đầy đủ thông tin chi tiết gửi đến Ban tổ chức để nhận phần thưởng nhé:

<ul>
  <li>Số Điện Thoại:</li>
  <li>Địa chỉ cụ thể:</li>
  <li>Scan hộ chiếu: </li>
    <li>Ngày về: </li>
	  <li>Số điện thoại người thân (trong trường hợp Vietjet không liên hệ bạn được)</li>
</ul>
											
												</span><br><br>
												<span style="text-align: justify;display: inline-block;">Chú ý:
												
	<ul>
  <li> Bạn vui lòng chủ động xin visa cho chuyến bay quốc tế. </li>
  <li>Bạn tuân thủ quy định theo điều lệ vận chuyển Vietjet tại www.vietjetair.com </li>
  <li>Bạn vui lòng cung cấp ngày về không trễ hơn 15/02/2019. </li>
    <li>Thông tin đăng kí để book vé đi và về sẽ không được thay đổi.</li>

</ul>
														
										
											
												</span>
												
         
                                                <br>
                            <span style="text-align: justify;display: inline-block;">
                              Cảm ơn Bạn luôn tin yêu đồng hành, hẹn gặp Bạn  trên các chuyến bay vui vẻ cùng Vietjet.
                            </span>
                                                <br>
                                                <br>
                                                <br>
                                                <span style="text-align: right; font-weight: 700; display: inline-block; width: 100%;">Trân trọng,</span>
                                                <br>
                            <span style="padding-top: 20px;text-align: right; font-weight: 700; display: inline-block; width: 100%;">
                              <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/logo-small.jpg" alt="">
                            </span>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td height="64" width="40" style="font-size:10px; line-height:10px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:10px; line-height:10px;">
                        <img src="<?php echo BASE_URL_SKIN_IMAGE; ?>/email/img-footer.jpg" alt="">
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>

</html>