<?php
$vFile = '?v='.time();
?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700|Poppins:200,300,400,600">
<link rel="stylesheet" href="<?php echo BASE_URL_SKIN_STYLESHEET; ?>/app.css">
<link rel="stylesheet" href="<?php echo BASE_URL_SKIN_DCUSTOM ?>/styles/dstyle.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" />