<?php
$vFile = '?v='.time();
?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700|Poppins:200,300,400,600">
<link id="link-css" rel="stylesheet" media="screen" href="<?php echo BASE_URL_SKIN_STYLESHEET; ?>/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo BASE_URL_SKIN_STYLESHEET; ?>/style.css">
<link rel="stylesheet" href="<?php echo BASE_URL_SKIN_STYLESHEET; ?>/login.css">
<link rel="stylesheet" href="<?php echo BASE_URL_SKIN_DCUSTOM; ?>/styles/dstyle.css<?php echo $vFile; ?>"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" />