<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<?php  echo $this->setting('core.GA_ID'); ?>"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<?php  echo $this->setting('core.GA_ID'); ?>');
</script>


<!-- Google Tag Manager (noscript) - ADD VAO TRONG OPEN THE BODY -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php  echo $this->setting('core.gg_manager_Id'); ?>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

