<?php
	$siteMeta = $this->layout()->siteMeta;
	$dataShare = $this->layout()->dataShare;
	$myLocale = $this->layout()->myLocale;
	$myLocaleShort = $this->layout()->myLocaleShort;


$action = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getParam('action', 'index');

$action = array_pop(explode('\'', $action));
	if($action=='detail'){
		$urlShare = 'https://'. $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];

		$siteName = $this->translate('Slogan');
		$title = $data['titleShare'];
		$description = $data['desShare'];
		$srcImage = $data['urlImage'];
	}elseif($dataShare){
		$siteName = $this->translate('Slogan');
	    $srcImage =	$dataShare['image'] ? $dataShare['image'] : BASE_URL_SKIN_IMAGE.'/social-share.png';
	    $title = $dataShare['title'] ? $dataShare['title'] : $siteMeta['title'];
	    $description = $this->translate('Share_story');
	    $urlShare = $dataShare['url'] ? $dataShare['url'] : BASE_URL;
	}else{
	    $siteName = $this->translate('Slogan');
		if($myLocaleShort=='vi'){
			$srcImage = BASE_URL_SKIN_IMAGE.'/og_img.jpg';
		}else{
			$srcImage = BASE_URL_SKIN_IMAGE.'/og_en.jpg';
		}

	    $title = $this->translate('Slogan');
	    $description = $this->translate('Share_story');
	    $urlShare = BASE_URL."/".$myLocaleShort;
	}

?>

<link rel="image_src" type="image/png" href="<?php echo $srcImage; ?>" />
<meta name="robots" content="index, follow" />
<meta name="revisit-after" content="3 days" />
<meta name="rating" content="general" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />

<meta property="fb:app_id" content="<?php echo FB_APP_ID; ?>"/>
<meta property="og:title" content="<?php echo $title; ?>" />
<meta property="og:type" content="website" />
<meta property="og:image" content="<?php echo $srcImage; ?>" />
<meta property="og:url" content="<?php echo $urlShare; ?>" />
<meta property="og:site_name" content="<?php echo $siteName; ?>" />
<meta property="og:description" content="<?php echo $description; ?>" />

<meta name="twitter:title" content="<?php echo $title; ?>">
<meta name="twitter:description" content="<?php echo $description; ?>">
<meta name="twitter:image:src" content="<?php echo $srcImage; ?>">
<meta name="twitter:url" content="<?php echo $urlShare; ?>">

<meta itemprop="name" content="<?php echo $title; ?>">
<meta itemprop="description" content="<?php echo $description; ?>">
<meta itemprop="image" content="<?php echo $srcImage; ?>">