<!-- Google Tag Manager (OWNED BY VIETJET) ADD VAO HEADER -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?php  echo $this->setting('core.gg_manager_Id'); ?>');</script>
<!-- End Google Tag Manager -->



<!-- Google Tag Manager (noscript) - ADD VAO TRONG OPEN THE BODY -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php  echo $this->setting('core.gg_manager_Id'); ?>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->