<?php
  $parentPage = $this->layout()->parent_page;
  $page = $this->layout()->page;

  $factory = $this->factory();
  $user = $this->user();
  $myLocale = $this->layout()->myLocale;
  $myLocaleShort = $this->layout()->myLocaleShort;
  $languageList = $factory->getLanguageList();
  $headerAddress = $factory->getPostByOptions('static_content_headeraddress', 1, $myLocale);
?>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Đóng/mở menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->setting('core.sitename') ?></a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
        <li><a href="javascript:;">Bài thi</a></li>
        <li><a href="javascript:;">Tin tức</a></li>
        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" >Demo <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->url('beantalk'); ?>">PHP Beantalk (Hàng đợi)</a></li>
            <li><a href="<?php echo $this->url('office-word'); ?>">PHP Word (Xuất ra file word)</a></li>
            <li><a href="<?php echo $this->url('handlebars'); ?>">PHP Handlebars vs ZF2</a></li>
          </ul>
        </li>

        <?php if (@$user && @$user['id']): ?>
          <li  class="dropdown">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" title="<?php echo $user['name']; ?>"><?php echo $user['name_fix']; ?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="javascript:;">Trang cá nhân</a></li>
              <li><a href="javascript:;">Thoát</a></li>
            </ul>
          </li>
        <?php else: ?>
          <li><a href="javascript:;">Đăng ký</a></li>
          <li><a href="javascript:;">Đăng nhập</a></li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
</div>
